server: 
  port: 9090

spring:
  application:
    name: pg-ms-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  jackson:
    time-zone: America/Bogota
  cloud:
    consul: 
      host: consul
      port: 8500
      discovery:
        register: true
        health-check-path: /actuator/health
        prefer-ip-address: false
        instance-id: ${spring.application.name}

    gateway:
      routes:
        - id: pg-ms-notifications-webhook
          uri: lb://pg-ms-notifications
          predicates:
            - Path=/api/webhooks/**

        - id: pg-ms-crewai-status
          uri: http://pg-ms-crewai:5000
          predicates:
            - Path=/api/status/**

        - id: pg-ms-crewai-chat
          uri: http://pg-ms-crewai:5000
          predicates:
            - Path=/api/chat/**

        - id: pg-ms-crewai-history
          uri: http://pg-ms-crewai:5000
          predicates:
            - Path=/api/history/**

        - id: pg-ms-crewai-history-clear
          uri: http://pg-ms-crewai:5000
          predicates:
            - Path=/api/history/clear/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: 3600000
biometric:
  jwt:
    secret-key: ${BIOMETRIC_JWT_SECRET}